### User login to get token
POST http://localhost:32785/realms/quarkus/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=alice&password=alice&client_id=backend-service&client_secret=secret

> {% client.global.set("token", response.body.access_token) %}

@token = {{token}}

### Get all users
GET http://localhost:8080/users
Authorization: Bearer {{token}}
Accept: application/json

### Get user by ID
GET http://localhost:8080/users/1
Authorization: Bearer {{token}}
Accept: application/json

### Create a new user
POST http://localhost:8080/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "username": "johndoe",
  "password": "password123"
}

### Update a user
PUT http://localhost:8080/users/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "John Doe Updated",
  "email": "john.doe.updated@example.com",
  "username": "johndoeupdated",
  "password": "newpassword123"
}

### Delete a user
DELETE http://localhost:8080/users/1
Authorization: Bearer {{token}}

### User login
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "johndoe",
  "password": "password123"
}

### Get all products
GET http://localhost:8080/products
Authorization: Bearer {{token}}
Accept: application/json

### Get product by ID
GET http://localhost:8080/products/1
Authorization: Bearer {{token}}
Accept: application/json

### Create a new product
POST http://localhost:8080/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "New Product",
  "price": 99.99
}

### Update a product
PUT http://localhost:8080/products/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 89.99
}

### Delete a product
DELETE http://localhost:8080/products/1
Authorization: Bearer {{token}}

### Get all carts
GET http://localhost:8080/carts
Authorization: Bearer {{token}}
Accept: application/json

### Get cart by ID
GET http://localhost:8080/carts/1
Authorization: Bearer {{token}}
Accept: application/json

### Create a new cart
POST http://localhost:8080/carts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 1,
  "totalPrice": 199.99,
  "products": []
}

### Update a cart
PUT http://localhost:8080/carts/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 1,
  "totalPrice": 299.99,
  "products": []
}

### Delete a cart
DELETE http://localhost:8080/carts/1
Authorization: Bearer {{token}}