name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x quarkus_app/gradlew

    - name: Build with Gradle
      run: ./quarkus_app/gradlew build

    - name: Run tests
      run: ./quarkus_app/gradlew test

    - name: Check code formatting
      run: ./quarkus_app/gradlew check

    - name: Pushing docker image
      run: ./quarkus_app/gradlew build -Dquarkus.container-image.push=true
      env:
        QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.QUARKUS_CONTAINER_IMAGE_USERNAME }}
        QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.QUARKUS_CONTAINER_IMAGE_PASSWORD }}
